version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: journal-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  springboot-app:
    build: .
    container_name: journal-app
    ports:
      - "8089:8089"
    depends_on:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_HOST: mongodb
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_DATABASE: JournalDB
      SERVER_PORT: 8089

volumes:
  mongo-data:
